### ISSUE TITLE
550 [...] is not a fully qualified domain name ("FQDN")

### ISSUE THREAD

**Issue by XFaktor** [forwardemail/free-email-forwarding-service#174]
Having problems sending mail due to the error 550 [...] is not a fully qualified domain name ("FQDN")

FROM GMAIL (to gmail, I'm not self hosted) 550 [209.85.208.48] is not a fully qualified domain name ("FQDN")

Also from yahoo and other providers the error is happening

<news@fraglider.pt>:
550: [74.6.130.40] is not a fully qualified domain name ("FQDN")

**Comment by tarkah** [comment]
Getting the same issue when sending mail from Gmail.  Seems to always occur if I add an alias (+) to the To address and always occurs when sending to my .net domain email, but not my other domains, such as .xyz, .io

I am having none of these issues sending from Office365

**Comment by rushilsrivastava** [comment]
Seems to be a problem I am facing on both `.tech` and `.com`. Lots of emails are not actually being delivered, seems to be a configuration problem with main host. Looking into self-hosting.

**Comment by lucaseverett** [comment]
I opened up #175 this morning due to what appears now to be the same issue. However, unlike @tarkah, I'm not receiving emails sent from my Office365 work email to any of my addresses being forwarded. I'm not getting an error, but nothing is being delivered to my Gmail addresses used for forwarding.

It was after trying to send myself an email from another Gmail account that I received the "is not a fully qualified domain name ("FQDN")" error, and was then able to connect my problem to the one being discussed here.

**Comment by dschofield** [comment]
Suffering same issue sending from Gmail to Gmail.

**Comment by niftylettuce** [comment]
Hi everyone - just had a little mini-vacation the past few days.  I will follow up as soon I can.  Thanks for being patient.  The FQDN issue is just because we have code in place that prevents IP's from sending emails that don't have a domain associated with them:

https://github.com/forwardemail/free-email-forwarding-service/blob/master/index.js#L270-L274

I can probably just comment this out for now and try to improve spam/virus filtering another way.

**Comment by niftylettuce** [comment]
I've resolved this issue and deployed a fix just now to production.  Emails should go through OK.  Gmail apparently decided to stop using FQDN as their sending IP addresses in the past 24-48 hours for some reason, I am uncertain 🙃

**Comment by tarkah** [comment]
@niftylettuce Thanks, all is working. Hope you had a nice few days off!
